export const FETCH_COURSELIST = 'FETCH_COURSELIST';
export const ADD_COURSE = "ADD_COURSE";
export const REMOVE_COURSE = "REMOVE_COURSE";
export const TOGGLE_COURSE_TERM = "TOGGLE_COURSE_TERM";
export const TOGGLE_COURSE = "TOGGLE_COURSE"
export const ADD_TEMP = "ADD_TEMP"
export const REMOVE_TEMP = "REMOVE_TEMP"



export const JUMP_TO = "JUMP_TO";
export const TOGGLE_TERM = "TOGGLE_TERM";
export const UPDATE_BREAKS = "UPDATE_BREAKS";

export const UPDATE_ACTIVE_SECTIONS = "UPDATE_ACTIVE_SECTIONS"
export const TOGGLE_LOCK = "TOGGLE_LOCK"